@extends("layouts.blank")
@section("content")
<div class="pulldown_contents privacy_container">
	<h1>Privacy policy</h1>	
    <div class="generic_layout_container layout_core_rich_text_block">
        <p class="MsoNormal"><span lang="EN-GB" style="font-size: 8pt;">This privacy policy applies between you, the User of this Website and Kinnect2 Limited, the owner and provider of this Website. Kinnect2 Limited takes the privacy of your information very seriously. This privacy policy applies to our use of any and all Data collected by us or provided by you in relation to your use of the Website. Please read this privacy policy carefully.</span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Definitions and interpretation</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;1. </span><!--[endif]--><span lang="EN-GB">In this privacy policy, the following definitions are used: </span></span></p>
        <table class="MsoNormalTable" style="margin-left: 2.75pt; border-collapse: collapse; border: none; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; mso-yfti-tbllook: 1184; mso-padding-alt: 2.75pt 2.75pt 2.75pt 2.75pt; mso-border-insideh: .25pt solid black; mso-border-insidev: cell-none;" border="1" cellspacing="0" cellpadding="0">
            <tbody>
            <tr>
                <td style="width: 334.2pt; border-top: solid black 1.0pt; border-left: none; border-bottom: solid black 1.0pt; border-right: none; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">Data</span></span></p>
                </td>
                <td style="width: 334.2pt; border-top: solid black 1.0pt; border-left: none; border-bottom: solid black 1.0pt; border-right: none; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">Collectively all information that you submit to Kinnect2 Limited via the Website. This definition incorporates, where applicable, the definitions provided in the Data Protection Act 1998;</span></p>
                </td>
            </tr>
            <tr>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">Cookies</span></span></p>
                </td>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">A small text file placed on your computer by this Website when you visit certain parts of the Website and/or when you use certain features of the Website. Details of the cookies used by this Website are set out in the clause below (Cookies);</span></p>
                </td>
            </tr>
            <tr>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">Kinnect2 Limited,</span><span lang="EN-GB"> or us</span></span></p>
                </td>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">Kinnect2 Limited, a company incorporated in England and Wales with registered number SC442762 whose registered office is at 95-107 LANCEFIELD STREET , Glasgow, G3 8HZ;</span></p>
                </td>
            </tr>
            <tr>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">UK and EU Cookie Law</span></span></p>
                </td>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">The Privacy and Electronic Communications (EC Directive) Regulations 2003 as amended by the Privacy and Electronic Communications (EC Directive) (Amendment) Regulations 2011;</span></p>
                </td>
            </tr>
            <tr>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">User</span><span lang="EN-GB"> or you</span></span></p>
                </td>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">Any third party that accesses the Website and is not either (i) employed by Kinnect2 Limited and acting in the course of their employment or (ii) engaged as a consultant or otherwise providing services to Kinnect2 Limited and accessing the Website in connection with the provision of such services; and</span></p>
                </td>
            </tr>
            <tr>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span style="font-size: 8pt;"><span lang="EN-GB">Website</span></span></p>
                </td>
                <td style="width: 334.2pt; border: none; border-bottom: solid black 1.0pt; mso-border-top-alt: solid black .25pt; mso-border-bottom-alt: solid black .25pt; padding: 2.75pt 2.75pt 2.75pt 2.75pt;" valign="top" width="446">
                    <p class="DefinitionDescription"><span lang="EN-GB" style="font-size: 8pt;">The website that you are currently using, kinnect2.com, and any sub-domains of this site unless expressly excluded by their own Terms and Conditions.</span></p>
                </td>
            </tr>
            </tbody>
        </table>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;2. </span><!--[endif]--><span lang="EN-GB">In this privacy policy, unless the context requires a different interpretation: </span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;a. </span><!--[endif]--><span lang="EN-GB">the singular includes the plural and vice versa;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;b. </span><!--[endif]--><span lang="EN-GB">references to sub-clauses, clauses, schedules or appendices are to sub-clauses, clauses, schedules or appendices of this privacy policy;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;c. </span><!--[endif]--><span lang="EN-GB">a reference to a person includes firms, companies, government entities, trusts and partnerships;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;d. </span><!--[endif]--><span lang="EN-GB">"including" is understood to mean "including without limitation";</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;e. </span><!--[endif]--><span lang="EN-GB">reference to any statutory provision includes any modification or amendment of it;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;f. </span><!--[endif]--><span lang="EN-GB">the headings and sub-headings do not form part of this privacy policy.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Scope of this privacy policy</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;3. </span><!--[endif]--><span lang="EN-GB">This privacy policy applies only to the actions of Kinnect2 Limited and Users with respect to this Website. It does not extend to any websites that can be accessed from this Website including, but not limited to, any links we may provide to social media websites.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Data collected</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;4. </span><!--[endif]--><span lang="EN-GB">We may collect the following Data, which includes personal Data, from you: </span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;a. </span><!--[endif]--><span lang="EN-GB">Name</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;b. </span><!--[endif]--><span lang="EN-GB">Date of Birth;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;c. </span><!--[endif]--><span lang="EN-GB">Gender;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;d. </span><!--[endif]--><span lang="EN-GB">Job Title;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;e. </span><!--[endif]--><span lang="EN-GB">Profession;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;f. </span><!--[endif]--><span lang="EN-GB">Contact Information such as email addresses and telephone numbers;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;g. </span><!--[endif]--><span lang="EN-GB">Demographic information such as post code, preferences and interests;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;h. </span><!--[endif]--><span lang="EN-GB">Financial information such as credit / debit card numbers;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;i. </span><!--[endif]--><span lang="EN-GB">IP address (automatically collected);</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;j. </span><!--[endif]--><span lang="EN-GB">Web browser type and version (automatically collected);</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;k. </span><!--[endif]--><span lang="EN-GB">Operating system (automatically collected);</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;l. </span><!--[endif]--><span lang="EN-GB">A list of URLs starting with a referring site, your activity on this Website, and the site you exit to (automatically collected);</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;m. </span><!--[endif]--><span lang="EN-GB">in each case, in accordance with this privacy policy.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Our use of Data</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;5. </span><!--[endif]--><span lang="EN-GB">For purposes of the Data Protection Act 1998, Kinnect2 Limited is the "data controller".</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;6. </span><!--[endif]--><span lang="EN-GB">We will retain any Data you submit for 12 months.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;7. </span><!--[endif]--><span lang="EN-GB">Unless we are obliged or permitted by law to do so, and subject to any third party disclosures specifically set out in this policy, your Data will not be disclosed to third parties. This does not include our affiliates and / or other companies within our group.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;8. </span><!--[endif]--><span lang="EN-GB">All personal Data is stored securely in accordance with the principles of the Data Protection Act 1998. For more details on security see the clause below (Security).</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;9. </span><!--[endif]--><span lang="EN-GB">Any or all of the above Data may be required by us from time to time in order to provide you with the best possible service and experience when using our Website. Specifically, Data may be used by us for the following reasons: </span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;a. </span><!--[endif]--><span lang="EN-GB">internal record keeping;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;b. </span><!--[endif]--><span lang="EN-GB">improvement of our products / services;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;c. </span><!--[endif]--><span lang="EN-GB">transmission by email of promotional materials that may be of interest to you;</span></span></p>
        <p class="MsoNormal" style="margin-left: 28.35pt; text-indent: -14.15pt; mso-list: l0 level2 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;d. </span><!--[endif]--><span lang="EN-GB">contact for market research purposes which may be done using email, telephone, fax or mail. Such information may be used to customise or update the Website;</span></span></p>
        <p class="MsoNormal"><span lang="EN-GB" style="font-size: 8pt;">in each case, in accordance with this privacy policy.</span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Third party websites and services</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;10. </span><!--[endif]--><span lang="EN-GB">Kinnect2 Limited may, from time to time, employ the services of other parties for dealing with certain processes necessary for the operation of the Website. The providers of such services do not have access to certain personal Data provided by Users of this Website.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Links to other websites</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;11. </span><!--[endif]--><span lang="EN-GB">This Website may, from time to time, provide links to other websites. We have no control over such websites and are not responsible for the content of these websites. This privacy policy does not extend to your use of such websites. You are advised to read the privacy policy or statement of other websites prior to using them.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Changes of business ownership and control</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;12. </span><!--[endif]--><span lang="EN-GB">Kinnect2 Limited may, from time to time, expand or reduce our business and this may involve the sale and/or the transfer of control of all or part of Kinnect2 Limited. Data provided by Users will, where it is relevant to any part of our business so transferred, be transferred along with that part and the new owner or newly controlling party will, under the terms of this privacy policy, be permitted to use the Data for the purposes for which it was originally supplied to us.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;13. </span><!--[endif]--><span lang="EN-GB">We may also disclose Data to a prospective purchaser of our business or any part of it.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;14. </span><!--[endif]--><span lang="EN-GB">In the above instances, we will take steps with the aim of ensuring your privacy is protected.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Controlling use of your Data</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;15. </span><!--[endif]--><span lang="EN-GB">Wherever you are required to submit Data, you will be given options to restrict our use of that Data. This may include the following:</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;16. </span><!--[endif]--><span lang="EN-GB">Use of Data for direct marketing purposes; and</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;17. </span><!--[endif]--><span lang="EN-GB">Sharing Data with third parties.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Functionality of the Website</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;18. </span><!--[endif]--><span lang="EN-GB">To use all features and functions available on the Website, you may be required to submit certain Data.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;19. </span><!--[endif]--><span lang="EN-GB">You may restrict your internet browser's use of Cookies. For more information see the clause below (Cookies).</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Accessing your own Data</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;20. </span><!--[endif]--><span lang="EN-GB">You have the right to ask for a copy of any of your personal Data held by Kinnect2 Limited (where such Data is held) on payment of a small fee, which will not exceed �5.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Security</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;21. </span><!--[endif]--><span lang="EN-GB">Data security is of great importance to Kinnect2 Limited and to protect your Data we have put in place suitable physical, electronic and managerial procedures to safeguard and secure Data collected via this Website.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;22. </span><!--[endif]--><span lang="EN-GB">If password access is required for certain parts of the Website, you are responsible for keeping this password confidential.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;23. </span><!--[endif]--><span lang="EN-GB">We endeavour to do our best to protect your personal Data. However, transmission of information over the internet is not entirely secure and is done at your own risk. We cannot ensure the security of your Data transmitted to the Website.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;"><a name="cookies">Cookies</a></span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;24. </span><!--[endif]--><span lang="EN-GB">This Website may place and access certain Cookies on your computer. Kinnect2 Limited uses Cookies to improve your experience of using the Website and to improve our range of products and services. Kinnect2 Limited has carefully chosen these Cookies and has taken steps to ensure that your privacy is protected and respected at all times.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;25. </span><!--[endif]--><span lang="EN-GB">All Cookies used by this Website are used in accordance with current UK and EU Cookie Law.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;26. </span><!--[endif]--><span lang="EN-GB">Before the Website places Cookies on your computer, you will be presented with a pop-up requesting your consent to set those Cookies. By giving your consent to the placing of Cookies, you are enabling Kinnect2 Limited to provide a better experience and service to you. You may, if you wish, deny consent to the placing of Cookies; however certain features of the Website may not function fully or as intended.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;27. </span><!--[endif]--><span lang="EN-GB">This Website may place the following Cookies:</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;28. </span><!--[endif]--><span lang="EN-GB">Type of CookiePurpose</span><span lang="EN-GB">Functionality cookiesThese are used to recognise you when you return to our website. This enables us to personalise our content for you, greet you by name and remember your preferences (for example, your choice of language or region).</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;29. </span><!--[endif]--><span lang="EN-GB">You can choose to enable or disable Cookies in your internet browser. By default, most internet browsers accept Cookies but this can be changed. For further details, please consult the help menu in your internet browser.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;30. </span><!--[endif]--><span lang="EN-GB">You can choose to delete Cookies at any time; however you may lose any information that enables you to access the Website more quickly and efficiently including, but not limited to, personalisation settings.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;31. </span><!--[endif]--><span lang="EN-GB">It is recommended that you ensure that your internet browser is up-to-date and that you consult the help and guidance provided by the developer of your internet browser if you are unsure about adjusting your privacy settings.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Transfers outside the European Economic Area</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;32. </span><!--[endif]--><span lang="EN-GB">Data which we collect from you may be stored and processed in and transferred to countries outside of the European Economic Area (EEA). For example, this could occur if our servers are located in a country outside the EEA or one of our service providers is situated in a country outside the EEA. We also share information with our group companies, some of which are located outside the EEA. These countries may not have data protection laws equivalent to those in force in the EEA.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;33. </span><!--[endif]--><span lang="EN-GB">If we transfer Data outside the EEA in this way, we will take steps with the aim of ensuring that your privacy rights continue to be protected as outlined in this privacy policy. You expressly agree to such transfers of Data.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">General</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;34. </span><!--[endif]--><span lang="EN-GB">You may not transfer any of your rights under this privacy policy to any other person. We may transfer our rights under this privacy policy where we reasonably believe your rights will not be affected.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;35. </span><!--[endif]--><span lang="EN-GB">If any court or competent authority finds that any provision of this privacy policy (or part of any provision) is invalid, illegal or unenforceable, that provision or part-provision will, to the extent required, be deemed to be deleted, and the validity and enforceability of the other provisions of this privacy policy will not be affected.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;36. </span><!--[endif]--><span lang="EN-GB">Unless otherwise agreed, no delay, act or omission by a party in exercising any right or remedy will be deemed a waiver of that, or any other, right or remedy.</span></span></p>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; mso-list: l0 level1 lfo1;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;37. </span><!--[endif]--><span lang="EN-GB">This privacy policy is governed by and interpreted according to English law. All disputes arising under this privacy policy are subject to the exclusive jurisdiction of the English courts.</span></span></p>
        <h2 style="text-align: justify;"><span lang="EN-GB" style="font-size: 8pt;">Changes to this privacy policy</span></h2>
        <p class="MsoNormal" style="margin-left: 14.15pt; text-indent: -14.15pt; text-align: justify;"><span style="font-size: 8pt;"><!--[if !supportLists]--><span lang="EN-GB">&nbsp;38. </span><!--[endif]--></span><span lang="EN-GB"><span style="font-size: 8pt;">Kinnect2 Limited reserves the right to change this privacy policy as we may deem necessary from time to time or as may be required by law. Any changes will be immediately posted on the Website and you are deemed to have accepted the terms of the privacy policy on your first use of the Website following the alterations.</span><br> <br><span style="font-size: 8pt;"> You may contact Kinnect2 Limited by email at info@kinnect2.com.</span><br> <br> <br><span style="font-size: 8pt;"> 07 September 2015</span></span></p></div>
</div>

@endsection
