<?php
$privacy = [
    'GEN'                   => 'General',//category
    'PRV'                   => 'Privacy',
    'BLOCKED'               => 'Blocked Members',
    'BLOCKED_PARA'          => "Adding a person to your block list makes your profile (and all of your other content) unviewable to them. Any connections you have to the blocked person will be canceled. To add someone to your block list, visit that person's profile page.",
    'DNT_DISPLY_ME_IN_SRCH' => 'Do not display me in searches, browsing members, or the "Online Members" list.',

    'P_PRV'         => 'Profile Privacy',
    'SEE_PROF'      => 'Who can view your profile?',
    'KIN_PRV'       => 'Kinnectors Privacy',
    'SEE_KIN'       => 'Who can view your kinnectors',
    'ONLY_ME'       => 'Only Me',
    'ONLY_MY_FRD'   => 'Only My Friends',
    'FRD_$_NETWRK'  => 'Friends & Network',
    'ALL_REG_MEMBR' => 'All Registered Members',

    'P_POSTING_PRV'     => 'Profile Posting Privacy',
    'WHO_POST_YUR_PROF' => 'Who can post on your profile?',

    'RECENT_ACTVTY_PRVCY' => 'Recent Activity Privacy',
    'RECENT_ACTVTY_PARA'  => 'Which of the following things do you want to have published about you in the recent activity feed? Note that changing this setting will only affect future news feed items.',

    'NEW_PHTO_ALBM'              => 'New photo albums',
    'NEW_BATLE'                  => 'New battles',
    'NEW_BLG_ENTRY'              => 'New blog entries',
    'NEW_BRND'                   => 'New brand',
    'JOING_BRND'                 => 'Joining a brand',
    'UPLOD_BRND_PHTO'            => 'Uploading a brand photo',
    'BRND_PROMTION'              => 'Brand promotions',
    'BRND_TG'                    => 'Brand Tag',
    'CRTNG_BRND_DISCUSION_TOPIC' => 'Creating a brand discussion topic',
    'REPLY_BRND_DISCUSIN_TOPIC'  => 'Replying to a brand discussion topic',
    'NEW_CLSFIED_LST'            => 'New classified listings',
    'COMENT_PHTO_ALBM'           => 'Comments on your photo albums',
    'COMENT_YUR_PHTO'            => 'Comments on your photos',
    'COMENT_YUR_BTL'             => 'Comments on your battles',
    'COMENT_YUR_BLG'             => 'Comments on your blogs',
    'COMENT_YUR_CLSFY_LSTIG'     => 'Comments on your classified listings',
    'COMENT_YUR_EVNT'            => 'Comments on your events',
    'COMENT_YUR_GRP'             => 'Comments on your groups',
    'COMENT_YUR_PLYLST'          => 'Comments on your playlists',
    'COMENT_YUR_POLL'            => 'Comments on your polls',
    'COMENT_YUR_VID'             => 'Comments on your videos',
    'NEW_EVTS'                   => 'New events',
    'JOING_EVT'                  => 'Joining an event',
    'UPL_EVT'                    => 'Uploading a photo to an event',
    'CRTNG_EVT_TOP'              => 'Creating an event discussion topic',
    'REPLY_EVT_DISCUSIN_TOPIC'   => 'Replying to an event discussion topic',
    'FORUM_PROMTION'             => 'Forum promotions',
    'CRTNG_FORUM_TOPIC'          => 'Creating a forum topic',
    'REPLY_FORUM_TOPIC'          => 'Replying to a forum topic',
    'WHN_BCME_WTH_SOMONE'        => 'When I become friends with someone',
    'NEW_GRP_POLL_ENTRY'         => 'New group poll entries',
    'NEW_GRP'                    => 'New groups',
    'JOIN_GRP'                   => 'Joining a group',
    'UPLOD_GRP_PHTO'             => 'Uploading a group photo',
    'GRP_PROMTON'                => 'Group promotions',
    'CRTNG_GRP_DISCUSION_TOPIC'  => 'Creating a group discussion topic',
    'REPLY_GRP_DISCUSION_TOPIC'  => 'Replying to a group discussion topic',
    'NEW_PLYLST'                 => 'New playlists',
    'REPLY_COMENT_ALBM'          => 'Replied to your comments on album',
    'REPLY_COMENT_ALB_PHTO'      => 'Replied to your comments on album photo',
    'REPLY_COMTENT_BLG'          => 'Replied to your comments on blog',
    'REPLY_COMENT_CLSFIED'       => 'Replied to your comments on classified',
    'NESTD_COMENT_EVT'           => 'Nested comment event',
    'REPLY_COMENT_GRP'           => 'Replied to your comments on group',
    'REPLY_COMENT_POLL'          => 'Replied to your comments on poll',
    'REPLY_COMENT_VID'           => 'Replied to your comments on video',
    'JOIN_NETWRK'                => 'Joining a network',
    'NEW_POLL'                   => 'New polls',
    'POSTNG_STATS_UPD_PROFILE'   => 'Posting a status update to your own profile',
    'CHGNG_PHTO'                 => 'Changing your photo',
    'ACTVTY_FEED_ITEM'           => 'Activity Feed Item Shared',
    'ACTVTY_ACTION_TG'           => 'Activity Action Type TAG',
    'TAG'                        => 'Tagged',
    'TG_BRND'                    => 'Tag to brand',
    'NEW_VID'                    => 'New videos',

];

$notification = [

    'NOTIFICATION' => 'Notification Settings.',

    'EMAIL_ALERT' => 'Which of the these do you want to receive email alerts about? .',

    'WEN_PEOPLE_COMTNS_ON_THING_I_POST'  => 'When people comment on things I post.',
    'WEN_PEOPLE_COMTNS_ON_SAME_THING_ME' => 'When people comment on the same thing as me.',
    'WEN_PEOPLE_ACPT_MY_FRND_REQUST'     => 'When someone accepts my friend request.',
    'WEN_I_RECIVE_A_FRND_REQUST'         => 'When I receive a friend request..',
    'WEN_PEOPLE_I_LIKE_THING_I_POST'     => 'When people like things I post.',
    'WEN_PEOPLE_COMTNS_ON_THING_I_LIKED' => "When people comment on things I've liked.",
    'WEN_PEOPLE_RPLY_ON_THING_I_LIKED'   => "When people reply on things I've liked.",
    'WEN_I_RECEIVE_MSG'                  => 'When I receive a message.',
    'WEN_PEOPLE_POST_ON_MY_PROFILE'      => 'When people post on my profile.',
    'WEN_PEOPLE_REPLY_ON_MY_PROFILE'     => 'When people reply on my posts..',
    'WEN_PEOPLE_REPLY_ON_SAME_THING_ME'  => 'When people reply on the same thing as me.',
    'WEN_ACTVITY_FEED_ITM_IS_SHARED'     => 'When activity feed item is shared.',
    'WEN_I_M_TAG_PHTO_&_OTHR_PLACE'      => "When I'm tagged in photos and other places",

    'WEN_I_GIVN_MODERATAR_STATUS_IN_FORUM'   => "When I'm given moderator status in a forum.",
    'WEN_PEOPLE_REPLY_FORUM_TOPIC_I_REPLIED' => "When people reply to forum topics that I've replied to.",
    'WEN_PEOPLE_REPLY_FORUM_THAT_I_CREATE'   => "When people reply to forum topics that I create.",

    'WEN_MY_REQUST_TO_JOIN_GRP_APPROVED'         => "When my request to join a group is approved.",
    'WEN_SOME_PEOPLE_REQUEST_JOIN_GRP_I_CREATED' => "When someone requests to join a group I created.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED'    => "When people reply to discussion topics that I've replied to.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE'     => "When people reply to discussion topics that I create.",
    'WEN_I_INVITE_TO_JOIN_GRP'                   => "When I'm invited to join a group.",
    'WEN_I_M_GIVN_STATUS_IN_GRP'                 => "When I'm given officer status in a group.",

    'WEN_NEW_BLG_ENTRY_POST_BY_MEMBR_U_SUBCRIBE' => "When a new blog entry is posted by a member you have subscribed to.",

    'WEN_MY_REQUST_TO_JOIN_BRND_APPROVED'          => "When my request to join a brand is approved.",
    'WEN_SOME_PEOPLE_REQUEST_JOIN_BRND_I_CREATED'  => "When someone requests to join a brand I created.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED_BRND' => "When people reply to discussion topics that I've replied to.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE_BRND'  => "When people reply to discussion topics that I create.",
    'WEN_I_INVITE_TO_JOIN_BRND'                    => "When I'm invited to join a brand.",
    'WEN_I_M_GIVN_STATUS_IN_BRND'                  => "When I'm given officer status in a brand.",

    'WEN_MY_REQUST_TO_ATTND_AN_EVT_APPROVED'       => "When my request to attend an event is approved.",
    'WEN_SOME_PEOPLE_REQUEST_TO_JOIN_MY_EVNT'      => "When someone request to join my event.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED_EVNT' => "When people reply to discussion topics that I've replied to.",
    'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE_EVNT'  => "When people reply to discussion topics that I create.",
    'WEN_I_INVITE_TO_ATTND_BRND'                   => "When I'm invited to attend an event.",

    'WEN_VID_PROCEED'            => "When a video has been processed.",
    'WEN_VID__FAILED_TO_PROCEED' => "When a video has failed to be processed.",

    'WEN_PEOPLE_COMENT_THING_I_FOLLOW' => "When people comment on things I follow.",
    'WEN_PEOPLE_LIKE_THING_I_FOLLOW'   => "When people like things I follow.",
    'WEN_I_M_TAG_IN_POST'              => "When I'm tagged in posts.",


];

$p = [
    'BLOCKED_MEMBERS'            => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Blocked Members',
        'DESCRIPTION' => 'Adding a person to your block list makes your profile (and all of your other content) unviewable to them. Any connections you have to the blocked person will be canceled. To add someone to your block list, visit that person\'s profile page. ',
        'OPTIONS'     => [
            'DNT_DISPLY_ME_IN_SRCH' => 'Do not display me in searches, browsing members, or the "Online Members" list.',
        ],
    ],
    'WHO_VIEW_PROFILE'           => [
        'TYPE'        => 'radio',
        'TITLE'       => 'Profile Privacy',
        'DESCRIPTION' => 'Who can view your profile?',
        'OPTIONS'     => [
            'ONLY_ME'       => 'Only Me',
            'ONLY_MY_FRD'   => 'Only My Friends',
            'FRD_$_NETWRK'  => 'Friends & Network',
            'ALL_REG_MEMBR' => 'All Registered Members',
        ],
    ], 'WHO_VIEW_KINNECTOR'      => [
        'TYPE'        => 'radio',
        'TITLE'       => 'Kinnectors Privacy',
        'DESCRIPTION' => 'Who can view your kinnectors?',
        'OPTIONS'     => [
            'ONLY_ME'       => 'Only Me',
            'ONLY_MY_FRD'   => 'Only My Friends',
            'FRD_$_NETWRK'  => 'Friends & Network',
            'ALL_REG_MEMBR' => 'All Registered Members',
        ],
    ], 'WHO_POST_YUR_PROFILE'    => [
        'TYPE'        => 'radio',
        'TITLE'       => 'Profile Posting Privacy',
        'DESCRIPTION' => 'Who can post on your profile?',
        'OPTIONS'     => [
            'ONLY_ME'       => 'Only Me',
            'ONLY_MY_FRD'   => 'Only My Friends',
            'FRD_$_NETWRK'  => 'Friends & Network',
            'ALL_REG_MEMBR' => 'All Registered Members',
        ],
    ], 'RECENT_ACTIVITY_PRIVACY' => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Recent Activity Privacy',
        'DESCRIPTION' => 'Which of the following things do you want to have published about you in the recent activity feed? Note that changing this setting will only affect future news feed items. ',
        'OPTIONS'     => [
            'NEW_PHTO_ALBM'              => 'New photo albums',
            'NEW_BATLE'                  => 'New battles',
            'NEW_BLG_ENTRY'              => 'New blog entries',
            'NEW_BRND'                   => 'New brand',
            'JOING_BRND'                 => 'Joining a brand',
            'UPLOD_BRND_PHTO'            => 'Uploading a brand photo',
            'BRND_PROMTION'              => 'Brand promotions',
            'BRND_TG'                    => 'Brand Tag',
            'CRTNG_BRND_DISCUSION_TOPIC' => 'Creating a brand discussion topic',
            'REPLY_BRND_DISCUSIN_TOPIC'  => 'Replying to a brand discussion topic',
            'NEW_CLSFIED_LST'            => 'New classified listings',
            'COMENT_PHTO_ALBM'           => 'Comments on your photo albums',
            'COMENT_YUR_PHTO'            => 'Comments on your photos',
            'COMENT_YUR_BTL'             => 'Comments on your battles',
            'COMENT_YUR_BLG'             => 'Comments on your blogs',
            'COMENT_YUR_CLSFY_LSTIG'     => 'Comments on your classified listings',
            'COMENT_YUR_EVNT'            => 'Comments on your events',
            'COMENT_YUR_GRP'             => 'Comments on your groups',
            'COMENT_YUR_PLYLST'          => 'Comments on your playlists',
            'COMENT_YUR_POLL'            => 'Comments on your polls',
            'COMENT_YUR_VID'             => 'Comments on your videos',
            'NEW_EVTS'                   => 'New events',
            'JOING_EVT'                  => 'Joining an event',
            'UPL_EVT'                    => 'Uploading a photo to an event',
            'CRTNG_EVT_TOP'              => 'Creating an event discussion topic',
            'REPLY_EVT_DISCUSIN_TOPIC'   => 'Replying to an event discussion topic',
            'FORUM_PROMTION'             => 'Forum promotions',
            'CRTNG_FORUM_TOPIC'          => 'Creating a forum topic',
            'REPLY_FORUM_TOPIC'          => 'Replying to a forum topic',
            'WHN_BCME_WTH_SOMONE'        => 'When I become friends with someone',
            'NEW_GRP_POLL_ENTRY'         => 'New group poll entries',
            'NEW_GRP'                    => 'New groups',
            'JOIN_GRP'                   => 'Joining a group',
            'UPLOD_GRP_PHTO'             => 'Uploading a group photo',
            'GRP_PROMTON'                => 'Group promotions',
            'CRTNG_GRP_DISCUSION_TOPIC'  => 'Creating a group discussion topic',
            'REPLY_GRP_DISCUSION_TOPIC'  => 'Replying to a group discussion topic',
            'NEW_PLYLST'                 => 'New playlists',
            'REPLY_COMENT_ALBM'          => 'Replied to your comments on album',
            'REPLY_COMENT_ALB_PHTO'      => 'Replied to your comments on album photo',
            'REPLY_COMTENT_BLG'          => 'Replied to your comments on blog',
            'REPLY_COMENT_CLSFIED'       => 'Replied to your comments on classified',
            'NESTD_COMENT_EVT'           => 'Nested comment event',
            'REPLY_COMENT_GRP'           => 'Replied to your comments on group',
            'REPLY_COMENT_POLL'          => 'Replied to your comments on poll',
            'REPLY_COMENT_VID'           => 'Replied to your comments on video',
            'JOIN_NETWRK'                => 'Joining a network',
            'NEW_POLL'                   => 'New polls',
            'POSTNG_STATS_UPD_PROFILE'   => 'Posting a status update to your own profile',
            'CHGNG_PHTO'                 => 'Changing your photo',
            'ACTVTY_FEED_ITEM'           => 'Activity Feed Item Shared',
            'ACTVTY_ACTION_TG'           => 'Activity Action Type TAG',
            'TAG'                        => 'Tagged',
            'TG_BRND'                    => 'Tag to brand',
            'NEW_VID'                    => 'New videos',
        ],
    ],
];

$n = [
    'GENERAL'          => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'General',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_PEOPLE_COMTNS_ON_THING_I_POST'  => 'When people comment on things I post.',
            'WEN_PEOPLE_COMTNS_ON_SAME_THING_ME' => 'When people comment on the same thing as me.',
            'WEN_PEOPLE_ACPT_MY_FRND_REQUST'     => 'When someone accepts my friend request.',
            'WEN_I_RECIVE_A_FRND_REQUST'         => 'When I receive a friend request..',
            'WEN_PEOPLE_I_LIKE_THING_I_POST'     => 'When people like things I post.',
            'WEN_PEOPLE_COMTNS_ON_THING_I_LIKED' => "When people comment on things I've liked.",
            'WEN_PEOPLE_RPLY_ON_THING_I_LIKED'   => "When people reply on things I've liked.",
            'WEN_I_RECEIVE_MSG'                  => 'When I receive a message.',
            'WEN_PEOPLE_POST_ON_MY_PROFILE'      => 'When people post on my profile.',
            'WEN_PEOPLE_REPLY_ON_MY_PROFILE'     => 'When people reply on my posts..',
            'WEN_PEOPLE_REPLY_ON_SAME_THING_ME'  => 'When people reply on the same thing as me.',
            'WEN_ACTVITY_FEED_ITM_IS_SHARED'     => 'When activity feed item is shared.',
            'WEN_I_M_TAG_PHTO_&_OTHR_PLACE'      => "When I'm tagged in photos and other places",

        ],
    ],
    'FORUM'            => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Forum',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_I_GIVN_MODERATAR_STATUS_IN_FORUM'   => "When I'm given moderator status in a forum.",
            'WEN_PEOPLE_REPLY_FORUM_TOPIC_I_REPLIED' => "When people reply to forum topics that I've replied to.",
            'WEN_PEOPLE_REPLY_FORUM_THAT_I_CREATE'   => "When people reply to forum topics that I create.",
        ],
    ], 'GROUPS'        => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Groups',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_MY_REQUST_TO_JOIN_GRP_APPROVED'         => "When my request to join a group is approved.",
            'WEN_SOME_PEOPLE_REQUEST_JOIN_GRP_I_CREATED' => "When someone requests to join a group I created.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED'    => "When people reply to discussion topics that I've replied to.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE'     => "When people reply to discussion topics that I create.",
            'WEN_I_INVITE_TO_JOIN_GRP'                   => "When I'm invited to join a group.",
            'WEN_I_M_GIVN_STATUS_IN_GRP'                 => "When I'm given officer status in a group.",

        ],
    ], 'BLOG'          => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Blog',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_NEW_BLG_ENTRY_POST_BY_MEMBR_U_SUBCRIBE' => "When a new blog entry is posted by a member you have subscribed to.",
        ],
    ], 'BRANDS'        => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Brands',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_MY_REQUST_TO_JOIN_BRND_APPROVED'          => "When my request to join a brand is approved.",
            'WEN_SOME_PEOPLE_REQUEST_JOIN_BRND_I_CREATED'  => "When someone requests to join a brand I created.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED_BRND' => "When people reply to discussion topics that I've replied to.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE_BRND'  => "When people reply to discussion topics that I create.",
            'WEN_I_INVITE_TO_JOIN_BRND'                    => "When I'm invited to join a brand.",
            'WEN_I_M_GIVN_STATUS_IN_BRND'                  => "When I'm given officer status in a brand.",
        ],
    ], 'EVENTS'        => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Events',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_MY_REQUST_TO_ATTND_AN_EVT_APPROVED'       => "When my request to attend an event is approved.",
            'WEN_SOME_PEOPLE_REQUEST_TO_JOIN_MY_EVNT'      => "When someone request to join my event.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_REPLIED_EVNT' => "When people reply to discussion topics that I've replied to.",
            'WEN_PEOPLE_REPLY_DISCUS_TOPIC_I_CREATE_EVNT'  => "When people reply to discussion topics that I create.",
            'WEN_I_INVITE_TO_ATTND_BRND'                   => "When I'm invited to attend an event.",
        ],
    ], 'Videos'        => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'Videos',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_VID_PROCEED'            => "When a video has been processed.",
            'WEN_VID__FAILED_TO_PROCEED' => "When a video has failed to be processed.",
        ],
    ],
    'YN_ADVANCED_FEED' => [
        'TYPE'        => 'multi-check',
        'TITLE'       => 'YN - Advanced Feed',
        'DESCRIPTION' => '',
        'OPTIONS'     => [
            'WEN_PEOPLE_COMENT_THING_I_FOLLOW' => "When people comment on things I follow.",
            'WEN_PEOPLE_LIKE_THING_I_FOLLOW'   => "When people like things I follow.",
            'WEN_I_M_TAG_IN_POST'              => "When I'm tagged in posts.",
        ],
    ],
];

return ['privacy' => $privacy, 'notification' => $notification, 'privacyApi' => $p, 'notificationApi' => $n];
